# Univariate Feature Imputation

In [2]:
import numpy as np
x=np.array([[np.nan,2],[6,np.nan],[10,37]])
x

array([[nan,  2.],
       [ 6., nan],
       [10., 37.]])

In [9]:
from sklearn.impute import SimpleImputer
imp=SimpleImputer(missing_values=np.nan,strategy="mean")
imp.fit_transform(x)

array([[ 8. ,  2. ],
       [ 6. , 19.5],
       [10. , 37. ]])

In [15]:
# For categorical features
import pandas as pd
df=pd.DataFrame([["h","s"],[np.nan,"k"],["d",np.nan],["g","k"]],dtype="category")
df

,0,1
0,h,s
1,NaN,k
2,d,NaN
3,g,k


imp_1=SimpleImputer(strategy="most_frequent")
print(imp_1.fit_transform(df))

# Multivariate Feature Imputation

In [18]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
imp_it=IterativeImputer(max_iter=10,random_state=7)
imp_it.fit_transform(x)

array([[ 2.000003  ,  2.        ],
       [ 6.        , 19.49999344],
       [10.        , 37.        ]])

In [20]:
# K-Nearest neighbour imputer
y=np.array([[1,2,np.nan],[10,37,np.nan],[np.nan,6,5],[8,8,7]])
y

array([[ 1.,  2., nan],
       [10., 37., nan],
       [nan,  6.,  5.],
       [ 8.,  8.,  7.]])

In [23]:
from sklearn.impute import KNNImputer
imputer=KNNImputer(n_neighbors=2,weights="uniform")
imputer.fit_transform(y)

array([[ 1. ,  2. ,  6. ],
       [10. , 37. ,  6. ],
       [ 4.5,  6. ,  5. ],
       [ 8. ,  8. ,  7. ]])