## Different ways of creating NumPy Arrays

In [1]:
import numpy as np

In [2]:
var1=np.array([1,2,3,4])
print(var1)

[1 2 3 4]


In [4]:
var2=np.array([[1,2,3],[4,5,6]])
print(var2)

[[1 2 3]
 [4 5 6]]


In [5]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.zeros([3,3],dtype="int")

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [9]:
np.ones([4,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
var3=np.ones([3,4],dtype="int")
print(var3)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [11]:
np.random.rand(4,4)

array([[0.93807861, 0.83477662, 0.26878626, 0.30364156],
       [0.41659298, 0.94273517, 0.9382095 , 0.43069539],
       [0.26729499, 0.93022137, 0.43309006, 0.04797271],
       [0.78591946, 0.62543786, 0.31540746, 0.0416842 ]])

In [12]:
r=np.random.rand(3,4)
print(r)

[[0.49515889 0.7018718  0.77580987 0.38273481]
 [0.65926624 0.22041752 0.78763891 0.81994975]
 [0.7707685  0.33961605 0.74798612 0.91455956]]


In [14]:
np.random.seed(3)
r2=np.random.rand(3,4)
print(r2)

[[0.5507979  0.70814782 0.29090474 0.51082761]
 [0.89294695 0.89629309 0.12558531 0.20724288]
 [0.0514672  0.44080984 0.02987621 0.45683322]]


In [16]:
np.random.randn(4,4)

array([[-1.31386475,  0.88462238,  0.88131804,  1.70957306],
       [ 0.05003364, -0.40467741, -0.54535995, -1.54647732],
       [ 0.98236743, -1.10106763, -1.18504653, -0.2056499 ],
       [ 1.48614836,  0.23671627, -1.02378514, -0.7129932 ]])

In [18]:
np.random.seed(4)
r2=np.random.randint(low=50,high=100,size=(3,4))
print(r2)

[[96 55 51 90]
 [73 58 59 89]
 [95 80 90 86]]


## Slicing and Indexing in Numpy Arrays

In [20]:
print(r2[1,1])

58


In [23]:
print(r2[2,3])

86


In [24]:
print(r2[1:,1:])

[[58 59 89]
 [80 90 86]]


In [26]:
print(r2[0:1,0:2])

[[96 55]]


In [29]:
print(r2[1:2,1:])

[[58 59 89]]


## Manipulation of an Array

In [30]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.identity(4,dtype="int")

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [33]:
ar1=np.arange(1,13).reshape(3,4)
print(ar1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [34]:
 ar1.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
ar1.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

## Stacking and Splitting of a Matrix

In [36]:
ar2=np.arange(1,21).reshape(4,5)
ar3=np.arange(21,41).reshape(4,5)
print(ar2)
print(ar3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]


In [38]:
np.vstack((ar2,ar3))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [39]:
np.hstack((ar2,ar3))

array([[ 1,  2,  3,  4,  5, 21, 22, 23, 24, 25],
       [ 6,  7,  8,  9, 10, 26, 27, 28, 29, 30],
       [11, 12, 13, 14, 15, 31, 32, 33, 34, 35],
       [16, 17, 18, 19, 20, 36, 37, 38, 39, 40]])

In [41]:
np.vsplit(ar2,2)

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])]

In [43]:
np.hsplit(ar1,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]