# Numpy

1. Full form: Numerical Python
2. When we want to create 1-D, 2-D & n-D arrays, we use numpy.
3. Only for numerical data type.

## Array

1. Array is an ordered data structure that contains data of similar type.
2. 1-D arrays contains only rows(direction).
3. 2-D arrays contains rows and columns(direction and magnitude).
4. 3-D arrays contains rows, columns and any third dimension.(E.g. images)

In [2]:
import numpy as np
ar=np.array([3,7,10,37])
print(ar)

[ 3  7 10 37]


In [3]:
ar_2=np.array((3,7,10,37,77))
print(ar_2)

[ 3  7 10 37 77]


In [5]:
ar_3=np.array(([3,7],[10,37]))
print(ar_3)

[[ 3  7]
 [10 37]]


In [7]:
ar_4=np.array(((1,2,3),(4,5,6),(7,8,9)))
print(ar_4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
import numpy as np
np.array([3,7,10,37],dtype="complex")

array([ 3.+0.j,  7.+0.j, 10.+0.j, 37.+0.j])

In [4]:
np.array([3,7,10,37],dtype="float")

array([ 3.,  7., 10., 37.])

## Differences between the numpy array and the list

In [13]:
# List in python:
l1=[3,7,10,37,77]
l2=[10,20,30,40,50]
print(l1+l2)

l=[]
for i,j in zip(l1,l2):
    l.append(i+j)
print(l)

[3, 7, 10, 37, 77, 10, 20, 30, 40, 50]
[13, 27, 40, 77, 127]


In [6]:
# List using numpy
import numpy as np
arr1=np.array((3,7,10,37,77))
arr2=np.array((10,20,30,40,50))
print(arr1+arr2)

[ 13  27  40  77 127]


1. Numpy arrays have fixed size of array creation(you cannot add or remove elements from it), but it is not the case when we talk about lists.
2. The elements in the numpy array are required to be of same data type, but this is not the case with the lists.
3. Numpy takes very less time to perform arithmetic activities between arrays whereas lists takes time.
4. Numpy arrays takes less space as compared to that of the space taken by the lists.

In [15]:
# to check the dimension of the array
arr1.ndim

1

In [17]:
# to check the shape of the matrix
ar_3=np.array(([3,7],[10,37]))
ar_3.shape

(2, 2)

In [18]:
# to find the size of the array
arr1.size

5

## Array Attributes

"arange" method helps us to create an array same as the range function in  1-D format.

In [20]:
a1=np.arange(10)
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
a2=np.arange(12,dtype="float")
print(a2)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


"reshape" method helps us to re shape any array.

In [22]:
a3=np.arange(12,dtype="float").reshape(4,3)
print(a3)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [23]:
a4=np.arange(10).reshape(2,5)
print(a4)

[[0 1 2 3 4]
 [5 6 7 8 9]]


"astype" is used to change the data type of any existing array.

In [34]:
a2.astype(np.int64)
print(a2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [32]:
a2*4

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44])

In [37]:
for i in a3:
    print(i)

[0. 1. 2.]
[3. 4. 5.]
[6. 7. 8.]
[ 9. 10. 11.]


"nditer" is used to traverse each element without nested loop in an array.

In [39]:
for i in np.nditer(a3):
    print(i)

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0


In [41]:
a3>5

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [42]:
a2>7

array([False, False, False, False, False, False, False, False,  True,
        True,  True,  True])